/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.panosmatsinopoulos.cancelcoroutine

import kotlinx.coroutines.*

fun main() {
    runBlocking {
        val startTime = System.currentTimeMillis()
        val job = launch(Dispatchers.Default) {
            var nextPrintTime = startTime
            var i = 0
            while (i < 5) {
                if (System.currentTimeMillis() >= nextPrintTime) {
                    println("job: I am sleeping ${i++}")
                    nextPrintTime += 500L
                }
            }
        }
        delay(1_300L)
        println("main: I'm tired of waiting!")
        job.cancelAndJoin()
        println("main: I can now quit")
    }
}
