/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.panosmatsinopoulos.cancelcoroutine

import kotlinx.coroutines.cancelAndJoin
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking

fun main() {
    runBlocking {
        val job = launch {
            repeat(1_000) { i ->
                println("job: I am sleeping $i ...")
                delay(500L)
            }
        }
        delay(1_300L)
        println("main: I'm tired waiting")
        job.cancelAndJoin()
        println("main. Now I can quit")
    }
}
